language: python
python:
  - "3.8"
dist: focal

before_install:
  - cd mysite
  - python manage.py migrate

install:
- pip install django
- pip install black
- pip install flake8
- pip install coverage
- pip install coveralls
- mkdir ./tools
- curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz -C ./tools

script:
  - black --check .
  - flake8
  - coverage run manage.py test
  - coverage xml
  - ./tools/coveralls report --repo-token=okYJYOMk5H4Qp3jMtETpVnYcKGHaFYwGI ./coverage.xml


deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-west-2"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-891537165702"

after_success:
  - coverage report
  - coveralls
