language: python
python:
  - "3.8"
dist: focal

before_install:
  - cd mysite

install:
  - pip install -r requirements.txt

script:
  - true

install:
  - pip install django
  - pip install black
  - pip install flake8
  - pip install coverage
  - pip install coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted <access-key-id>= $access_key_id"
  secret_access_key:
    secure: "Encypted <secret-access-key>= $secrete_access_key"
  region: "us-east-1"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-891537165702"