language: python
python:
  - "3.8"
dist: focal

before_install:
  - cd mysite

install:
  - pip install -r requirements.txt

script:
  - true

install:
  - pip install django
  - pip install black
  - pip install flake8
  - pip install coverage
  - pip install coveralls
