language: python
python:
  - "3.8"
dist: focal

before_install:
  - cd mysite

script:
  - black --check .
  - flake8
  - coverage run manage.py test
  - coverage report

install:
  - pip install -r requirements.txt
# cleaned up this section

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-west-2"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-891537165702"

after_success:
  - coveralls
