# Generated by Django 4.2.6 on 2023-10-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="pub_data",
            field=models.DateTimeField(db_column="pub_data"),
        ),
    ]
